; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
build_cache_dir = .pio/buildcache

[env]
platform = teensy
framework = arduino
monitor_speed = 115200
board = teensy40
lib_deps = forrest/TPS25751@^2.0.0

[env:example-read-downstream-bq25798-reg]
build_src_filter = +<*> +<../examples/read-downstream-bq25798-reg/src>

[env:example-bq25798-status]
build_src_filter = +<*> +<../examples/bq25798-status/src>

[env:example-bq25798-charge-config]
build_src_filter = +<*> +<../examples/bq25798-charge-config/src>

[env:example-bq25798-telemetry]
build_src_filter = +<*> +<../examples/bq25798-telemetry/src>

[env:example-bq25798-set-charge]
build_src_filter = +<*> +<../examples/bq25798-set-charge/src>

[env:example-bq25798-fault-investigator]
build_src_filter = +<*> +<../examples/bq25798-fault-investigator/src>

[env:example-bq25798-direct-i2c]
build_src_filter = +<*> +<../examples/bq25798-direct-i2c/src>
